name: WrapperApp

targets:
  WrapperApp:
    type: application
    platform: iOS
    sources:
      - path: .
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.wrapper

  Extension:
    type: app-extension
    platform: iOS
    sources:
      - path: extension
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.wrapper.extension
    dependencies:
      - target: WrapperApp
